# netlify.toml
# Configuración corregida de Netlify para Hospital Susana López de Valencia
# Portal de Gestión de Solicitudes con Supabase

[build]
  # Directorio de publicación (raíz del proyecto)
  publish = "."
  
  # Comando de build
  command = "echo 'Portal Hospital Susana López de Valencia - Supabase Ready'"

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# ===== CONFIGURACIÓN DE HEADERS HTTP =====

[[headers]]
  # Headers de seguridad para todos los archivos
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache general (1 hora)
    Cache-Control = "public, max-age=3600"
    
    # Headers CORS para Supabase y ESM modules
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey, prefer"

[[headers]]
  # Headers especiales para archivos JavaScript modules
  for = "*.js"
  [headers.values]
    # IMPORTANTE: Permitir módulos ES6
    Content-Type = "application/javascript"
    # Cache mediano para JS (4 horas)
    Cache-Control = "public, max-age=14400"
    # CORS para importación de módulos
    Access-Control-Allow-Origin = "*"

[[headers]]
  # Cache corto para archivos HTML (5 minutos)
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"
    # CSP para permitir importación de módulos externos
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://esm.sh https://cdn.jsdelivr.net; connect-src 'self' https://*.supabase.co wss://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[[headers]]
  # Cache largo para CSS (1 día)
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  # Cache muy largo para imágenes (7 días)
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# ===== CONFIGURACIÓN DE REDIRECTS =====

[[redirects]]
  # Página principal del portal
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Portal de solicitudes (ruta amigable)
  from = "/solicitudes"
  to = "/PORTALSOLICITUDES1.html"
  status = 200

[[redirects]]
  # Portal de gestión/mantenimiento (ruta amigable)
  from = "/gestion"
  to = "/PORTALMANTENIMIENTO1.html"
  status = 200

[[redirects]]
  # Portal de gestión/mantenimiento (ruta amigable)
  from = "/mantenimiento"
  to = "/PORTALMANTENIMIENTO1.html"
  status = 200

[[redirects]]
  # Alias para portal de gestión
  from = "/admin"
  to = "/PORTALMANTENIMIENTO1.html"
  status = 200

[[redirects]]
  # Alias para portal de solicitudes
  from = "/portal"
  to = "/PORTALSOLICITUDES1.html"
  status = 200

[[redirects]]
  # Alias para portal principal
  from = "/inicio"
  to = "/index.html"
  status = 200

[[redirects]]
  # Alias para portal principal
  from = "/home"
  to = "/index.html"
  status = 200

# Redirects para rutas con parámetros (mantener estado)
[[redirects]]
  from = "/solicitudes/*"
  to = "/PORTALSOLICITUDES1.html"
  status = 200

[[redirects]]
  from = "/gestion/*"
  to = "/PORTALMANTENIMIENTO1.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/PORTALMANTENIMIENTO1.html"
  status = 200

# Redirect especial para archivos de configuración
[[redirects]]
  from = "/config/*"
  to = "/config/:splat"
  status = 200

# Redirect para páginas no encontradas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# ===== CONFIGURACIÓN DE CONTEXTO =====

[context.production]
  # Configuraciones específicas para producción
  [context.production.environment]
    NODE_ENV = "production"
    ENVIRONMENT = "production"

[context.deploy-preview]
  # Configuraciones para preview de deploy
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    ENVIRONMENT = "preview"

[context.branch-deploy]
  # Configuraciones para deploys de branch
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    ENVIRONMENT = "branch"

# ===== CONFIGURACIÓN AVANZADA =====

[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = false  # Deshabilitado para preservar módulos ES6

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# ===== CONFIGURACIÓN DE EDGE HANDLERS =====
# Para funcionalidades avanzadas de Netlify Edge

[[edge_functions]]
  function = "cors-handler"
  path = "/api/*"

# ===== CONFIGURACIÓN DE FORMS =====

[forms]
  # Configuración para formularios de Netlify
  settings = { spam_protection = true }

# ===== CONFIGURACIÓN DE ANALYTICS =====

[analytics]
  # Habilitar analytics de Netlify
  enabled = true

# ===== CONFIGURACIÓN DE FUNCIONES =====

[functions]
  # Directorio de funciones serverless
  directory = "netlify/functions"
  
  # Configuración específica para Supabase
  [functions.environment]
    SUPABASE_URL = "https://tu-proyecto.supabase.co"
    SUPABASE_ANON_KEY = "tu-anon-key-aqui"

# ===== CONFIGURACIÓN DE VARIABLES DE ENTORNO =====

[template.environment]
  # Variables de template que serán reemplazadas
  SUPABASE_URL = "https://tu-proyecto.supabase.co"
  SUPABASE_ANON_KEY = "tu-anon-key-aqui"
  SITE_NAME = "Portal Hospital Susana López de Valencia"
  CONTACT_EMAIL = "soporte@hslvgestiondesolicitudes.com"

# ===== NOTAS IMPORTANTES =====

# Este archivo configura:
# ✅ Hosting estático optimizado para Supabase
# ✅ URLs amigables para los 3 portales
# ✅ Headers de seguridad y CORS apropiados
# ✅ Soporte para módulos ES6 e importaciones externas
# ✅ Cache optimizado por tipo de archivo
# ✅ Redirects para rutas no encontradas
# ✅ CSP configurado para Supabase
# ✅ Configuraciones por ambiente

# PASOS PARA CONFIGURAR:
# 1. Crear proyecto en Supabase
# 2. Ejecutar el schema SQL en Supabase
# 3. Obtener URL y anon key de Supabase
# 4. Actualizar config/supabase.js con credenciales reales
# 5. Subir archivos a repositorio Git
# 6. Conectar repositorio en Netlify
# 7. Configurar variables de entorno en Netlify
# 8. Deploy automático habilitado