# Redirects para la app
[[redirects]]
  from = "/app"
  to = "/app-tecnico.html"
  status = 200

# Headers para PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"



[build]
  # Directorio de funciones
  functions = "netlify/functions"
  
  # Directorio de publicación
  publish = "."
  
  # Comando de build (vacío porque es sitio estático)
  command = "echo 'Build completed'"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  
  # Instalar dependencias automáticamente
  NPM_FLAGS = "--production"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Headers específicos para las funciones
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PATCH, DELETE, OPTIONS"

# Redirects para URLs amigables
[[redirects]]
  from = "/portal"
  to = "/portal-solicitudes.html"
  status = 200

[[redirects]]
  from = "/gestion"
  to = "/portal-gestion.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test-netlify.html"
  status = 200