# Configuración de Netlify para Hospital Susana López de Valencia
[build]
  command = "echo 'Build completed successfully'"
  publish = "."
  functions = "netlify/functions"

# Headers mejorados para evitar CSP errors
[[headers]]
  for = "/*"
  [headers.values]
    # CORS headers
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, X-Requested-With"
    Access-Control-Max-Age = "86400"
    
    # Security headers (menos restrictivos para evitar CSP block)
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CSP más permisivo - permite conexiones internas y necesarias
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' /.netlify/functions/* https://*.netlify.app; img-src 'self' data: https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self';"

# Headers específicos para las funciones Netlify
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache para archivos estáticos
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configuración de funciones
[functions]
  directory = "netlify/functions"